export const TEXTOS = {
  comum: {
    acoes: 'Ações',
    novo: 'Novo',
    editar: 'Editar',
    excluir: 'Excluir',
    salvar: 'Salvar',
    cancelar: 'Cancelar',
    voltar: 'Voltar',
    pesquisar: 'Pesquisar',
    carregando: 'Carregando...',
    confirmacao: 'Confirmação',
    erro: 'Erro',
    sucesso: 'Sucesso',
  },
  marcas: {
    titulo: 'Marcas',
    novaMarca: 'Nova Marca',
    editarMarca: 'Editar Marca',
    nome: 'Nome da Marca',
    descricao: 'Descrição',
    status: 'Status',
    confirmacaoExclusao: 'Tem certeza que deseja excluir esta marca?',
    msgSucesso: 'Marca salva com sucesso!',
    msgErro: 'Erro ao salvar marca.',
  },
  validacoes: {
    campoObrigatorio: 'Este campo é obrigatório',
    tamanhoMinimo: 'Digite pelo menos {min} caracteres',
    tamanhoMaximo: 'Digite no máximo {max} caracteres',
  },
  status: {
    ativo: 'Ativo',
    inativo: 'Inativo',
  },
} as const;
