-- Create the loja table
create table if not exists public.loja (
    id bigint generated by default as identity primary key,
    nome varchar(255) not null,
    cnpj varchar(18) not null unique,
    endereco varchar(255) not null,
    numero varchar(10) not null,
    bairro varchar(100) not null,
    cidade varchar(100) not null,
    uf char(2) not null,
    cep varchar(9) not null,
    rede_id bigint references public.rede(id),
    promotor_id bigint references public.usuario(id),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create index for faster searches
create index if not exists loja_nome_idx on public.loja(nome);
create index if not exists loja_cidade_idx on public.loja(cidade);
create index if not exists loja_rede_id_idx on public.loja(rede_id);
create index if not exists loja_promotor_id_idx on public.loja(promotor_id);

-- Create trigger for updating updated_at
create or replace function public.handle_updated_at()
returns trigger as $$
begin
    new.updated_at = timezone('utc'::text, now());
    return new;
end;
$$ language plpgsql;

create trigger handle_loja_updated_at
    before update on public.loja
    for each row
    execute function public.handle_updated_at();
