-- Remove políticas existentes
drop policy if exists "Enable read access for authenticated users" on routes;
drop policy if exists "Enable insert access for authenticated users" on routes;
drop policy if exists "Enable update access for authenticated users" on routes;
drop policy if exists "Enable delete access for authenticated users" on routes;
drop policy if exists "Permitir leitura para usuários autenticados" on routes;
drop policy if exists "Permitir inserção para usuários autenticados" on routes;
drop policy if exists "Permitir atualização pelo próprio usuário" on routes;
drop policy if exists "Permitir exclusão pelo próprio usuário" on routes;
drop policy if exists "Permitir acesso público total" on routes;

-- Remove políticas existentes
drop policy if exists "Permitir acesso público total" on routes;

-- Recria a tabela routes
drop table if exists routes;
create table routes (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text,
    usuario_id bigint references usuario(id),
    stores jsonb,
    estimated_time integer,
    distance numeric
);

-- Habilita RLS
alter table routes enable row level security;

-- Cria política de acesso público
create policy "Permitir acesso público total"
on routes
for all
using (true)
with check (true);
